### ISSUE TITLE
JUnit Import in ActionHandler Causing Errors

### ISSUE THREAD

**Issue by GMOkeefe** [ncpalmie/Lab7-CSC365#3]
To be specific, the issue happens while building the program. The compiler has an issue where it cannot identify and correctly import the package ```org.junit.jupiter.api```, no matter what. I've tried all of the following:
- Putting the JUnit .jar on the ```CLASSPATH```
- Putting the JUnit .jar on the ```--module-path``` and adding the module ```org.junit.jupiter.api```
- Same as above except adding the module ```org.junit.jupiter.engine```
- Same as above except adding ```org.junit.jupiter.api``` and all of its dependencies.

I'm afraid I'm out of ideas. If you could add the correct method of compiling with that import statement to the README (it currently assumes that JUnit should be on the ```CLASSPATH``` which I now know to be incorrect), I would be grateful.

Also I've currently removed it from my branch in the interest of actually running the program, so don't let me forget to undo that (assuming it's critical) before I merge into master.

**Comment by ncpalmie** [comment]
I'm not sure how that import statement got there, looking through the commits it just appeared in one but I don't remember adding or needing it in ActionHandler so I believe it's fine to just remove it.
Which version of JUnit are you using though, as I was getting similar issues from the import in UnitTests until I started using JUnit 5.4.0.

**Comment by GMOkeefe** [comment]
I'm using the standalone launcher 1.6.0, which is the latest version. I don't have any issues running the UnitTests.

**Comment by ncpalmie** [comment]
Huh, weird. I also removed the import though and it runs fine so we're good without it.
